-- 코드를 입력하세요
SELECT
    A.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC;



/*
1. BOOK에 대한 판매량 * 판매가 계산 필요
2. AUTHOR 단위로 묶을 필요

*/