-- 코드를 입력하세요
SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    (FOOD_AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN (
        SELECT PRODUCT_ID, SUM(AMOUNT) AS FOOD_AMOUNT
        FROM FOOD_ORDER AS FO
        WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') IN ('2022-05') 
        GROUP BY PRODUCT_ID
    ) AS FA
ON FP.PRODUCT_ID = FA.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC;